<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
  <head>
    <?php echo $this->getChildHtml('head') ?>
    </head>
  <body <?php echo $this->getBodyClass()?'class="'.$this->getBodyClass().'"':'' ?>>
    <?php echo $this->getChildHtml('after_body_start') ?>

    <?php echo $this->getChildHtml('header') ?>
    
    <div class="content-wrapper">
	    <div id="content-container" class="container">
	      <div class="content">
	        
	        <?php echo $this->getChildHtml('global_notices') ?>
	        <?php echo $this->getChildHtml('global_messages') ?>
	        <?php echo $this->getChildHtml('content') ?>
	        <?php echo $this->getChildHtml('breadcrumbs') ?>
	      </div>

	    </div> <!-- /container -->
    </div>
    
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
   
  <?php echo $this->getAbsoluteFooter() ?>
  </body>
</html>